void initialize(void);
void singleStep(void);
double interpolatedValue(double *u, double *du);
double interpolatedDValue(double *u, double *du);
void fillStencilValues(int ind);
void debugPrint(void);
void debugGnuplot(void);
void fillStencilValues(int ind);
void debugPrint(void);
void debugGnuplot(void);
